### PR TITLE
Gradient macro for general finite differences and analytic RHF gradients

### PR DESCRIPTION
**Pull request by hfmull**
This adds the macro `@gradient` which functions similarly to `@energy`. It calls gradient methods specific to each energy method which currently only does finite differences except for RHF gradients which have analytic methods. However, the file structure is in place to easily add new analytic methods in future commits. Reference test data was gathered using Psi4.

### CODE REVIEW

**Comment by hfmull** [comment]
my tests are passing locally so I will have to figure out what the issue is after we get back

**Comment by gustavojra** [comment]
@hfmull it's not your code itself, it's the dependencies.

**Comment by hfmull** [comment]
The lack of patch coverage is mostly due to the gradient functions for methods other than RHF that call the finite differences function. It was tested with RHF, and repeating it with other methods would mostly just retest the energy methods its calling.

**Review by gustavojra — APPROVED** [review]
Beautiful

**Pull request merged**
